runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: (/user)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: required
  secure: optional
- url: (/user/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: required
  secure: optional
- url: (/admin)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/admin/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /user
  script: unused
  login: required
  secure: optional
- url: /user/.*
  script: unused
  login: required
  secure: optional
- url: /admin
  script: unused
  login: admin
  secure: optional
- url: /admin/.*
  script: unused
  login: admin
  secure: optional
- url: /.*
  script: unused
  login: optional
  secure: optional
